/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.ControladorInterface;

/**
 *
 * @author casa
 */
public class MonitoramentoPaciente extends javax.swing.JFrame {
    
    private ControladorInterface controlador;
    /**
     * Creates new form MonitoramentoPaciente1
     */
    public MonitoramentoPaciente(String nome) {
        initComponents();
        controlador = ControladorInterface.getInstancia();
      /*  nomePaciente.setText(controlador.buscarPaciente(nome).getNome());
        cpfPaciente.setText(controlador.buscarPaciente(nome).getCpf());
        gravPaciente.setText(" " +controlador.buscarPaciente(nome).getGravidade());
        pressaoPaciente.setText(" " +controlador.buscarPaciente(nome).getPressao()+" mmHg");
        fcPaciente.setText(" "+controlador.buscarPaciente(nome).getFreqCardiaca()+" bpm");
        respPaciente.setText(" " +controlador.buscarPaciente(nome).getFreqRespiratoria()+" mpm");
        saturPaciente.setText(" "+controlador.buscarPaciente(nome).getSatOxigenio()+"%");
        tempPaciente.setText(" "+controlador.buscarPaciente(nome).getTemperatura() + "ºC");*/
        nomePaciente.setText(nome);
        cpfPaciente.setText(nome);
        gravPaciente.setText(" " +nome);
        pressaoPaciente.setText(" " +nome+" mmHg");
        fcPaciente.setText(" "+nome+" bpm");
        respPaciente.setText(" " +nome+" mpm");
        saturPaciente.setText(" "+nome+"%");
        tempPaciente.setText(" "+nome+ "ºC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        respiracao = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        pressao = new javax.swing.JLabel();
        paciente = new javax.swing.JLabel();
        saturacao = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        temperatura = new javax.swing.JLabel();
        gravidade = new javax.swing.JLabel();
        freqCardiaca = new javax.swing.JLabel();
        nomePaciente = new javax.swing.JLabel();
        gravPaciente = new javax.swing.JLabel();
        cpfPaciente = new javax.swing.JLabel();
        tempPaciente = new javax.swing.JLabel();
        fcPaciente = new javax.swing.JLabel();
        respPaciente = new javax.swing.JLabel();
        pressaoPaciente = new javax.swing.JLabel();
        saturPaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        respiracao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        respiracao.setText("FREQUÊNCIA RESPIRATÓRIA:");

        Titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("SINAIS VITAIS");

        pressao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pressao.setText("PRESSÃO ARTERIAL SISTÓLICA:");

        paciente.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        paciente.setText("PACIENTE:");

        saturacao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        saturacao.setText("SATURAÇÃO DE OXIGÊNIO:");

        cpf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cpf.setText("CPF:");

        temperatura.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        temperatura.setText("TEMPERATURA:");

        gravidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        gravidade.setText("Nível de gravidade:");

        freqCardiaca.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        freqCardiaca.setText("FREQUÊNCIA CARDÍACA:");

        nomePaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nomePaciente.setText("jLabel1");

        gravPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gravPaciente.setText("jLabel1");

        cpfPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cpfPaciente.setText("jLabel1");

        tempPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tempPaciente.setText("jLabel1");

        fcPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fcPaciente.setText("jLabel1");

        respPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        respPaciente.setText("jLabel1");

        pressaoPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pressaoPaciente.setText("jLabel1");

        saturPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        saturPaciente.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cpfPaciente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paciente)
                                .addGap(18, 18, 18)
                                .addComponent(nomePaciente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(freqCardiaca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fcPaciente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(respiracao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(respPaciente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pressao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pressaoPaciente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saturacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saturPaciente))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(gravidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(temperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gravPaciente)
                                    .addComponent(tempPaciente))))))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paciente)
                    .addComponent(nomePaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpf)
                    .addComponent(cpfPaciente))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gravidade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gravPaciente))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temperatura)
                    .addComponent(tempPaciente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(freqCardiaca)
                    .addComponent(fcPaciente))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respiracao)
                    .addComponent(respPaciente))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pressao)
                    .addComponent(pressaoPaciente))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saturacao)
                    .addComponent(saturPaciente))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel cpfPaciente;
    private javax.swing.JLabel fcPaciente;
    private javax.swing.JLabel freqCardiaca;
    private javax.swing.JLabel gravPaciente;
    private javax.swing.JLabel gravidade;
    private javax.swing.JLabel nomePaciente;
    private javax.swing.JLabel paciente;
    private javax.swing.JLabel pressao;
    private javax.swing.JLabel pressaoPaciente;
    private javax.swing.JLabel respPaciente;
    private javax.swing.JLabel respiracao;
    private javax.swing.JLabel saturPaciente;
    private javax.swing.JLabel saturacao;
    private javax.swing.JLabel tempPaciente;
    private javax.swing.JLabel temperatura;
    // End of variables declaration//GEN-END:variables
}
